logging:
  level: error
  format: json

http_server:
  port: 8081
  request_timeout: 10

psql:
  host: localhost
  port: 5432
  database: test_app_sweetshop
  credentials:
    username: test_app_sweetshop
    password: test_app_sweetshop
  disable_ssl: true

otel:
  enabled: false
  service_name: sweetshop

rls:
  schema: app_sweetshop
  field: current_organization

middleware:
  recovery:
    enabled: true
  max_bytes:
    enabled: true
  request_id:
    enabled: true
  correlation_id:
    enabled: true
  otel_http:
    enabled: false
  request_log:
    enabled: false
